### ISSUE TITLE
Investigate and fix interaction with readline

### ISSUE THREAD

**Issue by rohitpaulk** [codecrafters-io/build-your-own-shell#29]
We recently saw test failures with JS/TS because they use [readline](https://nodejs.org/api/readline.html).

Here's what the error looked like: 

<img width="729" alt="Screenshot 2024-08-08 at 17 18 48" src="https://github.com/user-attachments/assets/bcb70165-f6f4-49f4-a055-24887e6bedb3">

We could hack around this by not using readline and using the stdin stream directly or wrapped in a buffer, but at some point in the future we will need to fix this — [readline](https://tiswww.case.edu/php/chet/readline/rltop.html) is very commonly used when building shells, and we'll offer it as an extension someday.

Let's look into what causes this error, and explore options to fix. Resources that might come in handy: 

- https://github.com/creack/pty - the pty library we use
- The [current expectation](https://github.com/codecrafters-io/shell-tester/blob/dcb0d928fae6cda632bde2b3acc02a6110abcf42/internal/shell_executable/shell_executable.go#L143) we have around writing to stdin on a pty, this is what caused the internal error we saw

We should spend time to make sure we understand this inside-out, wherever possible run experiments to verify our understanding. Some ideas: 

- Try readline bindings in other languages
  - Use [readline](https://ruby-doc.org/stdlib-2.5.1/libdoc/readline/rdoc/Readline.html) in Ruby, see if that triggers the same failure?
  - Use [readline](https://tiswww.case.edu/php/chet/readline/rltop.html) in C directly, see if that triggers the same failure?
  - This will tell us whether this behaviour is related to readline itself, or specific to Node's implementation of readline. 
- Look at the output we're receiving back when readline is used for JS/TS, what exactly is it returning? Try reading source code to reverse-engineer why extra data like that might be printed back.

**Comment by andy1li** [comment]
The new shell parser has fixed the issue.
